# Generated by Django 5.2.1 on 2025-05-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_pollresponse'),
        ('teacher', '0006_poll_polloption'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='responses',
            field=models.ManyToManyField(blank=True, related_name='poll_option', to='student.pollresponse'),
        ),
    ]
